name: Kernel Build

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    steps:
    - name: Free up disk space for the CI
      uses: AdityaGarg8/remove-unwanted-software@v5
      with:
       remove-android: 'true'
       remove-dotnet: 'true'
       remove-haskell: 'true'
       remove-codeql: 'true'
       remove-docker-images: 'true'
       remove-large-packages: 'true'
       remove-cached-tools: 'true'
       remove-swapfile: 'true'
    - name: 'Checkout Repo'
      uses: actions/checkout@v6
    - name: Build Kernel
      run: |
        git clone https://github.com/t2linux/linux-t2-patches.git
        cd linux-t2-patches
        git checkout 699c8fdf6e5d0c3bbd3487960df42881d4e8ffd9
        cd -
        #mkdir patches
        #cp ./linux-t2-patches/*patch ./patches
        #cd patches
        #ls > ../linux-t2-patches/list.conf
        #sed -i -e 's/^/pve\//' ../linux-t2-patches/list.conf
        #cd ..
        echo "APT::Get::Assume-Yes \"true\";" > ./90forceyes
        #echo "APT::Get::force-yes \"true\";" > ./90forceyes
        apt list --installed | cut -d "/" -f 1 | grep python | xargs > ./python-pkg
        for missing in python3-apport python3-commandnotfound python3-distupgrade python3-problem-report python3-update-manager python3.10-venv
        do
        sed -i -e "s/\<${missing}\>//g" ./python-pkg
        done

        DOCKER_IMAGE=debian:trixie
        docker pull ${DOCKER_IMAGE}
        docker run \
        --privileged \
        -t \
        -v "$(pwd)":/repo \
        ${DOCKER_IMAGE} \
        /bin/bash -c 'cd /repo && \
        cp ./90forceyes /etc/apt/apt.conf.d/90forceyes && \
        apt update && apt install wget && \
        echo "Types: deb" > /etc/apt/sources.list.d/pve-install-repo.sources && \
        echo "URIs: http://download.proxmox.com/debian/pve" >> /etc/apt/sources.list.d/pve-install-repo.sources && \
        echo "Suites: trixie" >> /etc/apt/sources.list.d/pve-install-repo.sources && \
        echo "Components: pve-no-subscription" >> /etc/apt/sources.list.d/pve-install-repo.sources && \
        echo "Signed-By: /usr/share/keyrings/proxmox-archive-keyring.gpg" >> /etc/apt/sources.list.d/pve-install-repo.sources && \
        wget https://enterprise.proxmox.com/debian/proxmox-archive-keyring-trixie.gpg -O /usr/share/keyrings/proxmox-archive-keyring.gpg && \ 
        apt modernize-sources && apt update && apt install asciidoc-base automake bc bison cpio debhelper dh-python file flex \
        gcc git kmod libdw-dev libelf-dev libiberty-dev libnuma-dev libslang2-dev libssl-dev libtool lintian lz4 dwarves libpve-common-perl python3-dev zstd \
        perl-modules rsync sed sphinx-common tar xmlto zlib1g-dev gawk && \
        #apt-get install $(cat ./python-pkg) && \
        git clone git://git.proxmox.com/git/pve-kernel.git && \
        cd pve-kernel && \
        cp ../linux-t2-patches/*patch ./patches/kernel && \
        cp ../T2.patch ./ && \
        git config --global user.email "example@example.com" && \
        git config --global user.name "Example Example" && \
        git am T2.patch && \
        #echo >> ./debian/patches/series.linux && \
        #cat ../linux-t2-patches/list.conf >> ./debian/patches/series.linux && \
        #cat ../linux-t2-patches/extra_config >> ./debian/config/config.pve && \
        #git submodule update --init --depth=1 --recursive linux && \
        #git submodule update --init --recursive && \
        #debian/rules debian/control && \
        #mk-build-deps -i && \
        KERNEL_SRC_SUBMODULE=submodules/ubuntu-kernel && \
        ZFSONLINUX_SUBMODULE=submodules/zfsonlinux && \
        git submodule update --depth 1 --init ${KERNEL_SRC_SUBMODULE} && \
        git submodule update --init --recursive ${ZFSONLINUX_SUBMODULE} && \
        make deb && \
        ls -l'
        #debuild -ePVE* --jobs=auto -b -uc -us'
    - name: Upload Artifacts
      uses: actions/upload-artifact@v5
      with:
        name: debs
        path: ${{ github.workspace }}/pve-kernel/*.deb
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ github.workspace }}/pve-kernel/*.deb
        tag_name: v6.17.4-1-t2-1
        body: |
          If you really like the work I am doing and wanna support me, consider donating here! :

          https://github.com/sponsors/AdityaGarg8

          https://www.buymeacoffee.com/gargadityav

          Your contribution shall be appreciated and be used in my education!. **It shall also keep me motivated to maintain this repository!**
        draft: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
